### ISSUE TITLE
Widen scope to anything that can deserialise to an arbitrary R object.

### ISSUE THREAD

**Issue by TimTaylor** [hrbrmstr/rdaradar#1]
E.g. No reason you couldn't get the same with the qs package deserialisation (AFAICT)

**Comment by hrbrmstr** [comment]
I have no context for that assertion. And, relying on a third-party package that has compiled C code is not something I'm likely interested in. Please feel encouraged to toss that out as an alternative solution if it is indeed an alternative solution.
